Temporary specifying version of connect
The latest version of `connect` (3.0.0) seems to cause some troubles; temporary specifying the latest known stable build (2.18.0).

```
Error: Cannot find module 'connect/lib/utils'
```